CREATE TABLE IF NOT EXISTS days (
  id TEXT PRIMARY KEY,
  nodes JSONB NOT NULL DEFAULT '[]'::jsonb,
  solution JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_progress (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
  day_id TEXT NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(email, day_id)
);


